### PR TITLE
ci-cd: build & deploy conda package

### PR DESCRIPTION
**Pull request by tngTUDOR**
+ version is taken from the "__init__.py" file for the conda package
+ conda package building "works (?)" and if you add the secrets to the repo, you can publish from workflow action
+ conda deploy action only runs when there is a "tag" in the commit (regarless of tag format, "0.1.3" or "v0.1.3" or "my 🌎 super tag" !

### CODE REVIEW

**Comment by tngTUDOR** [comment]
- [ ] verify if the "string" manipulation in the conda recipe is necessary or not. The package looks like it's python only, with a min version but I ignore if there are specific python version related parts of the code. if not, we could probably skip the "string" manipulation part of the recipe.

**Comment by TimoDiepers** [comment]
@tngTUDOR thanks a lot! I'm not sure what you mean with that though.

> * [ ]  verify if the "string" manipulation in the conda recipe is necessary or not. The package looks like it's python only, with a min version but I ignore if there are specific python version related parts of the code. if not, we could probably skip the "string" manipulation part of the recipe.

Are you referring to this? https://github.com/TimoDiepers/bw_timex_app/blob/2609561fe7f65c114bd75eaa9a4185b3b5ad61fe/conda/meta.yaml#L44

Because, tbh, I just copied this from somewhere where it was working.

**Comment by tngTUDOR** [comment]
Yes exactly.
I still haven't managed to test installing locally the built conda package bit the *build* works (even without the string part)

**Comment by TimoDiepers** [comment]
@tngTUDOR Does the entry point work for you?

**Comment by TimoDiepers** [comment]
> * [ ]  verify if the "string" manipulation in the conda recipe is necessary or not. The package looks like it's python only, with a min version but I ignore if there are specific python version related parts of the code. if not, we could probably skip the "string" manipulation part of the recipe.

Okay so I think I get this a bit more now - I just now saw how you just specified the python version to >=3.9. To me it looks like the string part is only used for "naming" the package files anyway - and it also seems to work without that for me.

**Comment by tngTUDOR** [comment]
The entry point works fine in the pypi package .

**Pull request merged**
